let { GraphQLString, GraphQLObjectType } = require('graphql');

const Master = new GraphQLObjectType({
  name: 'Mast',
  description: 'This represents everthing we were abel to extract from GDELT',
  fields: () => ({
    GLOBALEVENTID: { type: GraphQLString },
    SQLDATE: { type: GraphQLString },
    MonthYear: { type: GraphQLString },
    Year: { type: GraphQLString },
    FractionDate: { type: GraphQLString },
    Actor1Code: { type: GraphQLString },
    Actor1Name: { type: GraphQLString },
    Actor1CountryCode: { type: GraphQLString },
    Actor1KnownGroupCode: { type: GraphQLString },
    Actor1EthnicCode: { type: GraphQLString },
    Actor1Religion1Code: { type: GraphQLString },
    Actor1Religion2Code: { type: GraphQLString },
    Actor1Type1Code: { type: GraphQLString },
    Actor1Type2Code: { type: GraphQLString },
    Actor1Type3Code: { type: GraphQLString },
    Actor2Code: { type: GraphQLString },
    Actor2Name: { type: GraphQLString },
    Actor2CountryCode: { type: GraphQLString },
    Actor2KnownGroupCode: { type: GraphQLString },
    Actor2EthnicCode: { type: GraphQLString },
    Actor2Religion1Code: { type: GraphQLString },
    Actor2Religion2Code: { type: GraphQLString },
    Actor2Type1Code: { type: GraphQLString },
    Actor2Type2Code: { type: GraphQLString },
    Actor2Type3Code: { type: GraphQLString },
    IsRootEvent: { type: GraphQLString },
    EventCode: { type: GraphQLString },
    EventBaseCode: { type: GraphQLString },
    EventRootCode: { type: GraphQLString },
    QuadClass: { type: GraphQLString },
    GoldsteinScale: { type: GraphQLString },
    NumMentions: { type: GraphQLString },
    NumSources: { type: GraphQLString },
    NumArticles: { type: GraphQLString },
    AvgTone: { type: GraphQLString },
    Actor1Geo_Type: { type: GraphQLString },
    Actor1Geo_FullName: { type: GraphQLString },
    Actor1Geo_CountryCode: { type: GraphQLString },
    Actor1Geo_ADM1Code: { type: GraphQLString },
    Actor1Geo_Lat: { type: GraphQLString },
    Actor1Geo_Long: { type: GraphQLString },
    Actor1Geo_FeatureID: { type: GraphQLString },
    Actor2Geo_Type: { type: GraphQLString },
    Actor2Geo_FullName: { type: GraphQLString },
    Actor2Geo_CountryCode: { type: GraphQLString },
    Actor2Geo_ADM1Code: { type: GraphQLString },
    Actor2Geo_Lat: { type: GraphQLString },
    Actor2Geo_Long: { type: GraphQLString },
    Actor2Geo_FeatureID: { type: GraphQLString },
    ActionGeo_Type: { type: GraphQLString },
    ActionGeo_FullName: { type: GraphQLString },
    ActionGeo_CountryCode: { type: GraphQLString },
    ActionGeo_ADM1Code: { type: GraphQLString },
    ActionGeo_Lat: { type: GraphQLString },
    ActionGeo_Long: { type: GraphQLString },
    ActionGeo_FeatureID: { type: GraphQLString },
    DATEADDED: { type: GraphQLString },
    SOURCEURL: { type: GraphQLString },
  }),
});
module.exports = Master;
